### ISSUE TITLE
Difficulties to run own data set

### ISSUE THREAD

**Issue by tvetter1976** [AnetteEltner/FlowVeloTool#1]
I was able to run the tutorial. Now I wanted to run my own data using "stay in image space" first. When I run "Estimate flow velocity" I got the following message:

 `Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:/Users/tvetter/Desktop/Lfu/FlowVelo/code/FlowVeloTool/python3_version/GUI_FeatureDetectionTracking_v2.py", line 1286, in EstimateVelocity
    searchMask = ptv.searchMask(waterlevel_pt, waterlevel_buffer, AoI_file, ptCloud, unit_gcp, interior_orient,
  File "C:\Users\tvetter\Desktop\Lfu\FlowVelo\code\FlowVeloTool\python3_version\PTV_functions.py", line 102, in searchMask
    searchMask = np.asarray(searchMask)
UnboundLocalError: local variable 'searchMask' referenced before assignment`

Do I have to import search area? This checkbox is checked automatically when pressing "Estimate flow velocity".  How can I create such a file? Could you add an example file to the tutorial?

**Comment by jingwang960108** [comment]
searchMask is the point set of the waterfront dividing line, which needs to be labeled by yourself (such as labelme).

**Comment by AnetteEltner** [comment]
If you stay in image space you need to provide a mask of the river area. This should be a jpg or png with a binary mask with labelled water and not water, i.e. 1 and 0. You can prepare this mask with any image processing software.
