### ISSUE TITLE
GroundTruth of the river velocity

### ISSUE THREAD

**Issue by PlumedSerpent** [AnetteEltner/FlowVeloTool#2]
Is the ground truth velocity included in the dataset which is published on [opara](https://opara.zih.tu-dresden.de/xmlui/handle/123456789/1405)? Could you please upload the processing scripts for GroundTruth generation?

**Comment by AnetteEltner** [comment]
Yes, the ground truth velocities are also provided in opara. You can find it in the ADCP folder of each river. However, there is no processing script as we simply used approximated positions for the boat locations to fit the ADCP cross sections to the UAV maps.
